# Generated by Django 3.2.5 on 2021-07-28 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha Creacion')),
                ('android_id', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('montoabona', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('localidad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('nro', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=25)),
                ('contacto', models.CharField(max_length=50)),
                ('montodescuento', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cantidaddescuento', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('enviodomicilio', models.BooleanField(default=False, verbose_name='¿Envio a Domicilio?')),
                ('visto', models.BooleanField(default=False)),
                ('impreso', models.BooleanField(default=False)),
                ('tiempodemora', models.CharField(blank=True, default='00:45', max_length=10, null=True, verbose_name='Tiempo Demora')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('serie', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('valortexto', models.CharField(blank=True, max_length=100, null=True)),
                ('valorinteger', models.IntegerField(blank=True, default=0, null=True)),
                ('valordecimal', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('valorfecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha Creacion')),
                ('android_id', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('montoabona', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('localidad', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('piso', models.CharField(blank=True, max_length=10, null=True)),
                ('nro', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=25)),
                ('contacto', models.CharField(max_length=50)),
                ('montodescuento', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cantidaddescuento', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('enviodomicilio', models.BooleanField(default=False, verbose_name='¿Envio a Domicilio?')),
                ('visto', models.BooleanField(default=False)),
                ('impreso', models.BooleanField(default=False)),
                ('tiempodemora', models.CharField(blank=True, default='00:45', max_length=10, null=True, verbose_name='Tiempo Demora')),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('preciounitario', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('codigoexterno', models.CharField(blank=True, max_length=50, verbose_name='Codigo Externo')),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.CharField(blank=True, max_length=50)),
                ('enabled', models.BooleanField(default=True, verbose_name='¿Producto En Venta?')),
                ('ispromo', models.BooleanField(default=False, verbose_name='¿En Promocion?')),
                ('preciopromo', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Precio Promo')),
                ('isfraccionado', models.BooleanField(default=False, verbose_name='¿Es Fraccionado?')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Unidadmedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('enabled', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('preciopromo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('importedescuento', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('precioanterior', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fechadesde', models.DateTimeField(verbose_name='Fecha Hasta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='unidadmedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unidadmedida'),
        ),
        migrations.CreateModel(
            name='Pedidodetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.album')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'unique_together': {('album',)},
            },
        ),
    ]
