# Generated by Django 3.2.5 on 2021-07-28 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedido',
            name='horaentregado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora Entregado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='horarecepcion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora Recepcion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
