# Generated by Django 3.2.5 on 2021-07-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210728_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidaddescuento',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Descuento U.'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='montodescuento',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Descuento $'),
        ),
    ]
