# Generated by Django 3.2.5 on 2021-08-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210802_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('apertura', models.DateTimeField(verbose_name='Hora Apertura')),
                ('cierre', models.DateTimeField(verbose_name='Hora Cierre')),
                ('observaciones', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
