# Generated by Django 3.2.5 on 2021-08-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
    ]
