# Generated by Django 3.2.5 on 2021-08-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_horario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
