# Generated by Django 3.2.5 on 2021-08-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_horario_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='preciounitario',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
