# Generated by Django 3.2.5 on 2021-08-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userprofile_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
    ]
