# Generated by Django 3.2.5 on 2021-08-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210804_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='direccion',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='numero',
            new_name='nro',
        ),
    ]
