# Generated by Django 3.2.5 on 2021-08-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_userprofile_googlemaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='nropote',
            field=models.IntegerField(default=0),
        ),
    ]
